services:
  postgres:
    image: pgvector/pgvector:pg17

    container_name: quarry-postgres

    environment:
      POSTGRES_DB: quarry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1912

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: