services:

  api:
    build: .

    container_name: quarry-api

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: pgvector/pgvector:pg17

    container_name: quarry-postgres

    environment:
      POSTGRES_DB: quarry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1912

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: quarry-redis

    ports:
      - "6379:6379"

volumes:
  postgres_data: